# Change these first
owner: AayushmanChulet # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ihr
    url: https://www.ihr.live/
  - name: IHR Archive
    check: "tcp-ping"
    url: archive.ihr.live
    port: 80
  - name: IHR-Archive
    url: https://archive.ihr.live/ihr/
    expectedStatusCodes:
      - 200
    
  - name: IYP Database
    check: "tcp-ping"
    url: iyp-bolt.iijlab.net
    port: 443
  - name: iyp
    url: https://iyp.iijlab.net/
  - name: Countries API
    url: https://www.ihr.live/ihr/api/countries/?code=JP&format=json&name=Japan
    __dangerous__body_down_if_text_missing: '"code":"JP"'
  # - name: Neo4j HTTP API
  #   url: $NEO4J_URL/db/neo4j/tx/commit
  #   method: POST
  #   headers:
  #     - "Authorization: Basic $NEO4J_AUTH"
  #     - "Content-Type: application/json"
  #   body: '{"statements":[{"statement":"MATCH (n) RETURN count(n)"}]}'
  #   expectedStatusCodes:
  #     - 200
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Internet Health Report
  introTitle: Internet Health report
  introMessage: Hey this is an example status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
